################################################################
#### Initializing the Workers                              #####
################################################################
- name: STARTING JOIN KUBERNETES WORKERS
  hosts: worker_node
  vars_files: "/storage/automacao/ansible-files/kban-variables.yaml"
  tasks:
  - name: Loading variables
    ansible.builtin.include_vars:
      dir: "/"
      files_matching: kban-variables.yaml
  - name: Clean Previous Installations in Workers
    command: kubeadm reset -f
  # - name: Show Complete Command
  #   ansible.builtin.debug:
  #     msg: "{{ hostvars[groups['control_plane'][0]]['join_command'] }} --control-plane --certificate-key {{ hostvars[groups['control_plane'][0]]['join_command_key'] }}"
  - name: Executing Join Command in Workers
    command: "{{ hostvars[groups['control_plane'][0]]['join_command'] }}"

